---   
- name: Send Rocket.Chat alert
  community.general.rocketchat:
    token: hooks/66acad6c9b8a3e2fbeddd4d1/4MTnoqLehHGg6xkz7XT4ASniZTaSYvX45CFNTdL9HiBgjwwS
    domain: rocketchat.neotiq.com
    attachments:
      - text: Display my system load on host A and B
        color: #ff00dd
        title: System load
        fields:
          - title: System A
            value: 'load average: 0,74, 0,66, 0,63'
            short: true
          - title: System B
            value: 'load average: 5,16, 4,64, 2,43'
            short: true
  delegate_to: localhost
